services:
  zookeeper:
    image: bitnami/zookeeper:3.8.2
    restart: always
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - zookeeper_data:/bitnami/zookeeper/data
    ports:
      - "2181:2181"

  kafka:
    image: bitnami/kafka:3.5.1
    restart: always
    depends_on:
      - zookeeper
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - kafka_data:/bitnami/kafka/data
    ports:
      - "9092:9092"

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
